### ISSUE TITLE
Error LNK2019

### ISSUE THREAD

**Issue by Pacman187** [UnrealCourse/02_BullCowGame#10]
I copy and pasted the code and I still get this error, so it must be an update to visual studio 2017 that is causing the code to not run. Any help fixing this would be great.

1>main.obj : error LNK2019: unresolved external symbol "public: int __thiscall FBullCowGame::GetMaxTries(void)" (?GetMaxTries@FBullCowGame@@QAEHXZ) referenced in function "void __cdecl PlayGame(void)" (?PlayGame@@YAXXZ)
1>main.obj : error LNK2019: unresolved external symbol "public: int __thiscall FBullCowGame::GetCurrentTry(void)" (?GetCurrentTry@FBullCowGame@@QAEHXZ) referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl GetGuess(void)" (?GetGuess@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)

**Comment by sampattuzzi** [comment]
@Pacman187 can you share your code?

**Comment by Pacman187** [comment]
Thanks for getting back to me Sam. I actually pasted courses code from here https://github.com/UnrealCourse/02_BullCowGame/commit/6111258f3dd5d49b537ece2bdcdede663072a99f 
and I still get the error this is causing me to believe its because of an update to visual studio, I really want to continue to course but have stopped because I can't get the code to work.

**Comment by sampattuzzi** [comment]
Do you have GetMaxTries in your header?

**Comment by Pacman187** [comment]
This is what I have `#pragma once
#include <string>

class FBullCowGame {
public:
	void Reset(); // TODO make a more rich return value.
	int GetMaxTries();
	int GetCurrentTry();
	bool IsGameWon();
	bool CheckGuessValidity(std::string); // TODO make a more rich return value.


										  // ^^ Please try and ignore this and focus on the interface above ^^
private:
	int MyCurrentTry = 1;
	int MyMaxTries = 5;
};`

**Comment by Pacman187** [comment]
for `main
#include <iostream>
#include <string>	
#include "FBullCowGame.h"

void PrintIntro();
void PlayGame();
std::string GetGuess();
bool AskToPlayAgain();

FBullCowGame BCGame; // instantiate a new game

					 // the entry point for our application
int main()
{
	bool bPlayAgain = false;
	do {
		PrintIntro();
		PlayGame();
		bPlayAgain = AskToPlayAgain();
	} while (bPlayAgain);

	return 0; // exit the application
}


// introduce the game
void PrintIntro()
{
	constexpr int WORLD_LENGTH = 9;
	std::cout << "Welcome to Bulls and Cows, a fun word game.\n";
	std::cout << "Can you guess the " << WORLD_LENGTH;
	std::cout << " letter isogram I'm thinking of?\n";
	std::cout << std::endl;
	return;
}


void PlayGame()
{
	int MaxTries = BCGame.GetMaxTries();

	// loop for the number of turns asking for guesses
	for (int count = 1; count <= MaxTries; count++) {
		std::string Guess = GetGuess();
		std::cout << "Your guess was: " << Guess << std::endl;
		std::cout << std::endl;
	}
}


std::string GetGuess()
{
	int CurrentTry = BCGame.GetCurrentTry();

	// get a guess from the player
	std::cout << "Try " << CurrentTry << ". Enter your guess: ";
	std::string Guess = "";
	std::getline(std::cin, Guess);
	return Guess;
}

bool AskToPlayAgain()
{
	std::cout << "Do you want to play again (y/n)? ";
	std::string Response = "";
	std::getline(std::cin, Response);
	return (Response[0] == 'y') || (Response[0] == 'Y');
}

**Comment by Pacman187** [comment]
//fbullcowgame.cpp

#include "FBullCowGame.h"

int FBullCowGame::GetMaxTries() { return MyMaxTries; }
int FBullCowGame::GetCurrentTry() { return MyCurrentTry; }

void FBullCowGame::Reset()
{
	return;
}

bool FBullCowGame::IsGameWon()
{
	return false;
}

bool FBullCowGame::CheckGuessValidity(std::string)
{
	return false;
}

**Comment by Pacman187** [comment]
I'm also getting this error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	2 unresolved externals	BullCowGame	C:\Users\Sic\Documents\Visual Studio 2017\Projects\Unreal Class\Section_02\Section_02\Debug\BullCowGame.exe	1

**Comment by sampattuzzi** [comment]
I suggest you ask this question in the Q&A where it will be visible to our student instructors who will be able to respond faster than us. It's also really hard to read your code snippets when you paste them without proper formatting. I would recommend sharing them over in the Q&A with a link to a Gist. Please also include there details of what you did to set up your project and which visual studio version you are using.

**Comment by chris-joseph** [comment]
hey i too don't understand linker errors but i have a temporary solution, just change 👍 
in main:
#include "FBullCowGame.h" to #include "FBullCowGame.cpp" 
don't delete the .h file tho it works ,hope it was helpful
#10 LNK 2019
