### ISSUE TITLE
NUMBER_OF_TURNS Wont work

### ISSUE THREAD

**Issue by Perrottacooking** [UnrealCourse/02_BullCowGame#12]
#include <iostream>
#include <string> 

void PrintIntro();
std::string GetGuessAndPrintBack();

int main()
{
	PrintIntro();
	const int NUMBER_OF_TURNS = 5;
	for (int count = 1; count <= 5 NUMBER_OF_TURNS; count++) {
		GetGuessAndPrintBack();
	}
}
void PrintIntro() {
	const int WORLD_LENGHT = 9;
	std::cout << "  Welcome to Bulls and Cows, a fun word game.\n";
	std::cout << "Can you guess the " << WORLD_LENGHT << " letter isogram i thinking of?\n";
}
// usuario conseguindo que utilisa e escreve na tela
std::string GetGuessAndPrintBack() {
	std::cout << "Enter your guess: ";
	std::string Guess = "";// string com nada dentro.
	getline(std::cin, Guess);
	std::cout << " Your guess wass: " << Guess << std::endl;
	return Guess;
}

**Comment by NitezYagiro** [comment]
for (int count = 1; count <= 5 NUMBER_OF_TURNS; count++) { << try without this number 5 in frot of NUMBER_OF_TURNS

**Comment by Perrottacooking** [comment]
thanks
