### ISSUE TITLE
Whole Project got corrupted

### ISSUE THREAD

**Issue by itsyaboyleroy** [UnrealCourse/02_BullCowGame#8]
Basically my entire project has been messed up and I want to know how I can download the entire project from github at the bc16 state.

Thanks,
Leroy

**Comment by BenTristem** [comment]
Hi there, click the green "Clone or download" button at this link...

https://github.com/UnrealCourse/02_BullCowGame/tree/0be266f6f2e5eaaf8f4c04a5918786a2236718b4

Good luck!
